CREATE TABLE Status (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    Stat_name VARCHAR(255) NOT NULL
);

CREATE TABLE People (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    First_Name VARCHAR(255) NOT NULL,
    Last_Name VARCHAR(255) NOT NULL,
    GID VARCHAR(50),
    City VARCHAR(255),
    Street VARCHAR(255),
    Male_Child INT DEFAULT 0,
    Female_Child INT DEFAULT 0,
    Status_ID INT,
    Notes TEXT,
    Join_Date DATE,
    FOREIGN KEY (Status_ID) REFERENCES Status(ID) ON DELETE SET NULL
);

CREATE TABLE Helping (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    Helping_name VARCHAR(255) NOT NULL
);

CREATE TABLE People_Helping (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    People_ID INT,
    Helping_ID INT,
    Value DECIMAL(10,2),
    Notes TEXT,
    Date DATE,
    FOREIGN KEY (People_ID) REFERENCES People(ID) ON DELETE CASCADE,
    FOREIGN KEY (Helping_ID) REFERENCES Helping(ID) ON DELETE CASCADE
);
